### ISSUE TITLE
use-workspace-logstash-if-exists.tar.gz is missing

### ISSUE THREAD

**Issue by drnic** [logsearch/logsearch-for-websites#2]
`bin/install_dependencies` is looking for https://github.com/logsearch/logsearch-filters-common/archive/use-workspace-logstash-if-exists.tar.gz but it is missing

**Comment by mrdavidlaing** [comment]
@drnic - oops - deleted that branch when I merged https://github.com/logsearch/logsearch-filters-common/pull/22

Link should now be fixed - could you try again please
